export const FETCH_IROH_ACCOUNTS = 'FETCH_IROH_ACCOUNTS';
export const FETCH_IROH_ACCOUNTS_SUCCESS = 'FETCH_IROH_ACCOUNTS_SUCCESS';
export const FETCH_IROH_ACCOUNTS_FAILURE = 'FETCH_IROH_ACCOUNTS_FAILURE';
export const FETCH_DISCORD_ACCOUNTS = 'FETCH_DISCORD_ACCOUNTS';
export const FETCH_DISCORD_ACCOUNTS_SUCCESS = 'FETCH_DISCORD_ACCOUNTS_SUCCESS';
export const FETCH_DISCORD_ACCOUNTS_FAILURE = 'FETCH_DISCORD_ACCOUNTS_FAILURE';