export const SWITCH_PAGE = 'SWITCH_PAGE';
export const FETCH_IMAGE_CATEGORY_PAGE = 'FETCH_IMAGE_CATEGORY_PAGE';
export const FETCH_IMAGE_CATEGORY_PAGE_SUCCESS = 'FETCH_IMAGE_CATEGORY_PAGE_SUCCESS';
export const FETCH_IMAGE_CATEGORY_PAGE_FAILURE = 'FETCH_IMAGE_CATEGORY_PAGE_FAILURE';
export const CYCLE_NSFW = 'CYCLE_NSFW';
