export const FETCH_IMAGE_INFO = 'FETCH_IMAGE_INFO';
export const FETCH_IMAGE_INFO_SUCCESS = 'FETCH_IMAGE_INFO_SUCCESS';
export const FETCH_IMAGE_INFO_FAILURE = 'FETCH_IMAGE_INFO_FAILURE';
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const DELETE_IMAGE_CONFIRM = 'DELETE_IMAGE_CONFIRM'
export const DELETE_IMAGE_CANCEL = 'DELETE_IMAGE_CANCEL'
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE'
